package codegen

const mainTemplateSource = `// Code generated by clihub v{{.ClihubVersion}}. DO NOT EDIT.
package main

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcpclient "github.com/mark3labs/mcp-go/client"
{{- if .IsHTTP}}
	"github.com/mark3labs/mcp-go/client/transport"
{{- end}}
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/spf13/cobra"
	"golang.org/x/oauth2/google"
)

// --- Embedded server configuration ---
{{- if .IsHTTP}}
const serverURL = {{quote .ServerURL}}
{{- else}}
var stdioCommand = {{quote .StdioCommand}}
var stdioArgs = {{quoteSlice .StdioArgs}}
var envKeys = {{quoteSlice .EnvKeys}}
{{- end}}

// --- Global flags ---
var (
	globalTimeout        int
	globalOutput         string
	globalAuthToken      string
	globalAuthType       string
	globalAuthHeaderName string
	globalAuthUsername   string
	globalAuthPassword   string
)

func main() {
	rootCmd := &cobra.Command{
		Use:   {{quote .CLIName}},
		Short: {{quote (printf "CLI for %s MCP server" .CLIName)}},
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	rootCmd.PersistentFlags().IntVarP(&globalTimeout, "timeout", "t", 30000, "per-call timeout in milliseconds")
	rootCmd.PersistentFlags().StringVarP(&globalOutput, "output", "o", "text", "output format: text|json|markdown|raw")
	rootCmd.PersistentFlags().StringVar(&globalAuthToken, "auth-token", "", "bearer token for authenticated MCP servers")
	rootCmd.PersistentFlags().StringVar(&globalAuthType, "auth-type", "", "authentication type: bearer, api_key, basic, none")
	rootCmd.PersistentFlags().StringVar(&globalAuthHeaderName, "auth-header-name", "", "custom header name for api_key auth (default X-API-Key)")
	rootCmd.PersistentFlags().StringVar(&globalAuthUsername, "auth-username", "", "username for basic auth")
	rootCmd.PersistentFlags().StringVar(&globalAuthPassword, "auth-password", "", "password for basic auth")

{{- range .Tools}}
	rootCmd.AddCommand(cmd{{funcName .Name}}())
{{- end}}

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}
}

// --- Tool commands ---
{{range .Tools}}
func cmd{{funcName .Name}}() *cobra.Command {
{{- range .Options}}
	var {{varName .FlagName}} {{.GoType}}
{{- end}}
	var flagRaw string

	cmd := &cobra.Command{
		Use:     {{quote .CommandName}},
		Aliases: []string{ {{quote .Name}} },
		Short:   {{quote .Description}},
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			params := make(map[string]interface{})
			if flagRaw != "" {
				if err := json.Unmarshal([]byte(flagRaw), &params); err != nil {
					return fmt.Errorf("invalid --raw JSON: %w", err)
				}
			} else {
{{- range .Options}}
{{- if eq .GoType "string"}}
				if {{varName .FlagName}} != "" {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "int"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "float64"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "bool"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "[]string"}}
				if len({{varName .FlagName}}) > 0 {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "[]int"}}
				if len({{varName .FlagName}}) > 0 {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- end}}
{{- end}}
			}
{{range .Options}}{{if .EnumValues}}
			// Validate enum for {{.FlagName}}
			if v, ok := params[{{quote .PropertyName}}]; ok {
				if s, ok := v.(string); ok {
					valid := {{quoteSlice .EnumValues}}
					found := false
					for _, e := range valid {
						if s == e {
							found = true
							break
						}
					}
					if !found {
						return fmt.Errorf("invalid value %q for --%s: must be one of: %s", s, {{quote .FlagName}}, strings.Join(valid, ", "))
					}
				}
			}
{{end}}{{end}}
			return callTool({{quote .Name}}, params)
		},
	}

{{- range .Options}}
	cmd.Flags().{{cobraFlag .GoType}}(&{{varName .FlagName}}, {{quote .FlagName}}, {{defaultLit .GoType .DefaultValue}}, {{quote (hasEnumDesc .Description .EnumValues)}})
{{- end}}
	cmd.Flags().StringVar(&flagRaw, "raw", "", "raw JSON arguments (bypasses all other flags)")

	return cmd
}
{{end}}

// --- MCP client via mcp-go SDK ---

func callTool(toolName string, params map[string]interface{}) error {
	provider := resolveAuthProvider()

	timeout := time.Duration(globalTimeout) * time.Millisecond
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	c, err := createClient(ctx, provider)
	if err != nil {
		return err
	}
	defer c.Close()

{{- if .IsHTTP}}
	// Start HTTP transport
	if err := c.Start(ctx); err != nil {
		if ctx.Err() != nil {
			return fmt.Errorf("tool call timed out after %dms", globalTimeout)
		}
		return fmt.Errorf("MCP connection failed: %w", err)
	}
{{- end}}

	// Initialize handshake
	initReq := mcp.InitializeRequest{}
	initReq.Params.ProtocolVersion = mcp.LATEST_PROTOCOL_VERSION
	initReq.Params.ClientInfo = mcp.Implementation{Name: {{quote .CLIName}}, Version: "1.0.0"}
	initReq.Params.Capabilities = mcp.ClientCapabilities{}

	if _, err := c.Initialize(ctx, initReq); err != nil {
		if ctx.Err() != nil {
			return fmt.Errorf("tool call timed out after %dms", globalTimeout)
		}
		return fmt.Errorf("MCP handshake failed: %w", err)
	}

	// Call tool
	callReq := mcp.CallToolRequest{}
	callReq.Params.Name = toolName
	callReq.Params.Arguments = params

	result, err := c.CallTool(ctx, callReq)
	if err != nil {
		if ctx.Err() != nil {
			return fmt.Errorf("tool call timed out after %dms", globalTimeout)
		}
		return fmt.Errorf("tool call failed: %w", err)
	}
	if result.IsError {
		// Extract error text from content
		var errTexts []string
		for _, content := range result.Content {
			if tc, ok := content.(mcp.TextContent); ok {
				errTexts = append(errTexts, tc.Text)
			}
		}
		if len(errTexts) > 0 {
			return fmt.Errorf("tool error: %s", strings.Join(errTexts, "\n"))
		}
		return fmt.Errorf("tool returned an error")
	}

	return formatOutput(result, globalOutput)
}

func createClient(ctx context.Context, provider authProvider) (*mcpclient.Client, error) {
{{- if .IsHTTP}}
	var opts []transport.StreamableHTTPCOption
	headers := provider.getHeaders(ctx)
	if len(headers) > 0 {
		opts = append(opts, transport.WithHTTPHeaderFunc(func(ctx context.Context) map[string]string {
			return provider.getHeaders(ctx)
		}))
	}
	return mcpclient.NewStreamableHttpClient(serverURL, opts...)
{{- else}}
	// Build environment for subprocess
	env := os.Environ()
	for _, key := range envKeys {
		val := os.Getenv(key)
		if val == "" {
			return nil, fmt.Errorf("required environment variable %s is not set", key)
		}
	}
	return mcpclient.NewStdioMCPClient(stdioCommand, env, stdioArgs...)
{{- end}}
}

// --- Output formatting ---

func formatOutput(result *mcp.CallToolResult, format string) error {
	switch format {
	case "json":
		data, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			return err
		}
		fmt.Println(string(data))

	case "raw":
		data, err := json.Marshal(result)
		if err != nil {
			return err
		}
		fmt.Println(string(data))

	default: // "text", "markdown"
		text := extractText(result)
		fmt.Println(text)
	}
	return nil
}

func extractText(result *mcp.CallToolResult) string {
	var parts []string
	for _, content := range result.Content {
		switch c := content.(type) {
		case mcp.TextContent:
			parts = append(parts, c.Text)
		default:
			// For non-text content, marshal to JSON
			data, err := json.Marshal(c)
			if err == nil {
				var pretty bytes.Buffer
				if json.Indent(&pretty, data, "", "  ") == nil {
					parts = append(parts, pretty.String())
				} else {
					parts = append(parts, string(data))
				}
			}
		}
	}
	if len(parts) > 0 {
		return strings.Join(parts, "\n")
	}
	// Fallback: marshal the whole result
	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return fmt.Sprintf("%+v", result)
	}
	return string(data)
}

// --- Auth provider dispatch ---

type authProvider interface {
	getHeaders(ctx context.Context) map[string]string
}

type noAuthProvider struct{}
func (p *noAuthProvider) getHeaders(_ context.Context) map[string]string { return nil }

type bearerTokenProvider struct{ token string }
func (p *bearerTokenProvider) getHeaders(_ context.Context) map[string]string {
	if p.token == "" { return nil }
	return map[string]string{"Authorization": "Bearer " + p.token}
}

type apiKeyProvider struct{ token, headerName string }
func (p *apiKeyProvider) getHeaders(_ context.Context) map[string]string {
	if p.token == "" { return nil }
	name := p.headerName
	if name == "" { name = "X-API-Key" }
	return map[string]string{name: p.token}
}

type basicAuthProvider struct{ username, password string }
func (p *basicAuthProvider) getHeaders(_ context.Context) map[string]string {
	if p.username == "" && p.password == "" { return nil }
	encoded := base64.StdEncoding.EncodeToString([]byte(p.username + ":" + p.password))
	return map[string]string{"Authorization": "Basic " + encoded}
}

type s2sOAuth2Provider struct {
	clientID, clientSecret, tokenEndpoint string
	cachedToken string
}
func (p *s2sOAuth2Provider) getHeaders(ctx context.Context) map[string]string {
	if p.cachedToken == "" {
		token, err := s2sAuthenticate(ctx, p.tokenEndpoint, p.clientID, p.clientSecret)
		if err != nil {
			return nil
		}
		p.cachedToken = token
	}
	return map[string]string{"Authorization": "Bearer " + p.cachedToken}
}

type googleSAProvider struct {
	keyFile string
	scopes  []string
}
func (p *googleSAProvider) getHeaders(ctx context.Context) map[string]string {
	keyData, err := os.ReadFile(p.keyFile)
	if err != nil { return nil }
	scopes := p.scopes
	if len(scopes) == 0 {
		scopes = []string{"https://www.googleapis.com/auth/cloud-platform"}
	}
	creds, err := google.CredentialsFromJSON(ctx, keyData, scopes...)
	if err != nil { return nil }
	token, err := creds.TokenSource.Token()
	if err != nil { return nil }
	return map[string]string{"Authorization": "Bearer " + token.AccessToken}
}

// --- Credential store types ---

type credentialsFile struct {
	Servers map[string]serverCredential ` + "`" + `json:"servers"` + "`" + `
}

type serverCredential struct {
	AuthType      string    ` + "`" + `json:"auth_type"` + "`" + `
	Type          string    ` + "`" + `json:"type"` + "`" + `
	Token         string    ` + "`" + `json:"token"` + "`" + `
	AccessToken   string    ` + "`" + `json:"access_token"` + "`" + `
	RefreshToken  string    ` + "`" + `json:"refresh_token"` + "`" + `
	ExpiresAt     string    ` + "`" + `json:"expires_at"` + "`" + `
	ClientID      string    ` + "`" + `json:"client_id"` + "`" + `
	ClientSecret  string    ` + "`" + `json:"client_secret"` + "`" + `
	TokenEndpoint string    ` + "`" + `json:"token_endpoint"` + "`" + `
	HeaderName    string    ` + "`" + `json:"header_name"` + "`" + `
	Username      string    ` + "`" + `json:"username"` + "`" + `
	Password      string    ` + "`" + `json:"password"` + "`" + `
	KeyFile       string    ` + "`" + `json:"key_file"` + "`" + `
	Scopes        []string  ` + "`" + `json:"scopes"` + "`" + `
}

func (s serverCredential) resolveAuthType() string {
	if s.AuthType != "" { return s.AuthType }
	switch s.Type {
	case "bearer": return "bearer_token"
	case "oauth": return "oauth2"
	default: return s.Type
	}
}

func (s serverCredential) isExpired() bool {
	if s.ExpiresAt == "" { return false }
	t, err := time.Parse(time.RFC3339, s.ExpiresAt)
	if err != nil { return false }
	return time.Now().After(t)
}

// --- Token refresh ---

func refreshOAuthToken(credPath, srvURL string, sc serverCredential) (string, error) {
	if sc.RefreshToken == "" {
		return "", fmt.Errorf("access token expired and no refresh token available. Run ` + "`" + `clihub generate --url %s --auth-type oauth2` + "`" + ` to re-authenticate", srvURL)
	}
	tokenEndpoint := sc.TokenEndpoint
	if tokenEndpoint == "" {
		return "", fmt.Errorf("access token expired and no token endpoint stored. Run ` + "`" + `clihub generate --url %s --auth-type oauth2` + "`" + ` to re-authenticate", srvURL)
	}

	form := url.Values{
		"grant_type":    {"refresh_token"},
		"client_id":     {sc.ClientID},
		"refresh_token": {sc.RefreshToken},
	}

	resp, err := http.Post(tokenEndpoint, "application/x-www-form-urlencoded", strings.NewReader(form.Encode()))
	if err != nil {
		return "", fmt.Errorf("token refresh request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("token refresh failed (%d): %s. Run ` + "`" + `clihub generate --url %s --auth-type oauth2` + "`" + ` to re-authenticate", resp.StatusCode, string(body), srvURL)
	}

	var tokenResp struct {
		AccessToken  string ` + "`" + `json:"access_token"` + "`" + `
		RefreshToken string ` + "`" + `json:"refresh_token"` + "`" + `
		ExpiresIn    int    ` + "`" + `json:"expires_in"` + "`" + `
	}
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return "", fmt.Errorf("parse refresh response: %w", err)
	}

	if tokenResp.AccessToken == "" {
		return "", fmt.Errorf("refresh response missing access_token")
	}

	// Update credential store
	data, err := os.ReadFile(credPath)
	if err == nil {
		var creds credentialsFile
		if json.Unmarshal(data, &creds) == nil && creds.Servers != nil {
			entry := creds.Servers[srvURL]
			entry.AccessToken = tokenResp.AccessToken
			if tokenResp.RefreshToken != "" {
				entry.RefreshToken = tokenResp.RefreshToken
			}
			if tokenResp.ExpiresIn > 0 {
				entry.ExpiresAt = time.Now().Add(time.Duration(tokenResp.ExpiresIn) * time.Second).Format(time.RFC3339)
			}
			creds.Servers[srvURL] = entry
			if updated, err := json.MarshalIndent(creds, "", "  "); err == nil {
				os.WriteFile(credPath, updated, 0600)
			}
		}
	}

	return tokenResp.AccessToken, nil
}

// --- S2S OAuth2 ---

func s2sAuthenticate(ctx context.Context, tokenEndpoint, clientID, clientSecret string) (string, error) {
	form := url.Values{
		"grant_type":    {"client_credentials"},
		"client_id":     {clientID},
		"client_secret": {clientSecret},
	}

	req, err := http.NewRequestWithContext(ctx, "POST", tokenEndpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return "", fmt.Errorf("S2S token request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("S2S token endpoint returned %d: %s", resp.StatusCode, string(body))
	}

	var tokenResp struct {
		AccessToken string ` + "`" + `json:"access_token"` + "`" + `
	}
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return "", fmt.Errorf("parse S2S response: %w", err)
	}
	if tokenResp.AccessToken == "" {
		return "", fmt.Errorf("S2S response missing access_token")
	}
	return tokenResp.AccessToken, nil
}

// resolveAuthProvider builds an auth provider using the following priority:
//  1. --auth-type + auth flags → explicit provider
//  2. --auth-token without --auth-type → bearer (backwards compat)
//  3. CLIHUB_AUTH_TOKEN env var → bearer
//  4. Credentials file → provider from stored auth_type (with token refresh)
//  5. No credentials → no auth
func resolveAuthProvider() authProvider {
	// 1. Explicit --auth-type
	if globalAuthType != "" {
		switch globalAuthType {
		case "bearer", "bearer_token":
			return &bearerTokenProvider{token: globalAuthToken}
		case "api_key":
			return &apiKeyProvider{token: globalAuthToken, headerName: globalAuthHeaderName}
		case "basic", "basic_auth":
			return &basicAuthProvider{username: globalAuthUsername, password: globalAuthPassword}
		default:
			return &noAuthProvider{}
		}
	}

	// 2. --auth-token without --auth-type → infer bearer
	if globalAuthToken != "" {
		return &bearerTokenProvider{token: globalAuthToken}
	}

	// 3. CLIHUB_AUTH_TOKEN env var
	if token := os.Getenv("CLIHUB_AUTH_TOKEN"); token != "" {
		return &bearerTokenProvider{token: token}
	}

	// 4. Credentials file
	credPath := os.Getenv("CLIHUB_CREDENTIALS_FILE")
	if credPath == "" {
		home, err := os.UserHomeDir()
		if err == nil {
			credPath = filepath.Join(home, ".clihub", "credentials.json")
		}
	}
	if credPath != "" {
		data, err := os.ReadFile(credPath)
		if err == nil {
			var creds credentialsFile
			if json.Unmarshal(data, &creds) == nil && creds.Servers != nil {
{{- if .IsHTTP}}
				if s, ok := creds.Servers[serverURL]; ok {
					authType := s.resolveAuthType()
					switch authType {
					case "bearer_token":
						return &bearerTokenProvider{token: s.Token}
					case "api_key":
						return &apiKeyProvider{token: s.Token, headerName: s.HeaderName}
					case "basic_auth":
						return &basicAuthProvider{username: s.Username, password: s.Password}
					case "oauth2":
						token := s.AccessToken
						if s.isExpired() && s.RefreshToken != "" {
							refreshed, err := refreshOAuthToken(credPath, serverURL, s)
							if err != nil {
								fmt.Fprintf(os.Stderr, "Warning: %s\n", err)
							} else {
								token = refreshed
							}
						}
						return &bearerTokenProvider{token: token}
					case "s2s_oauth2":
						return &s2sOAuth2Provider{
							clientID: s.ClientID, clientSecret: s.ClientSecret,
							tokenEndpoint: s.TokenEndpoint,
						}
					case "google_sa":
						return &googleSAProvider{keyFile: s.KeyFile, scopes: s.Scopes}
					}
				}
{{- end}}
			}
		}
	}

	// 5. No auth
	return &noAuthProvider{}
}
`

const goModTemplateSource = `module {{.CLIName}}

go 1.23

require (
	github.com/mark3labs/mcp-go v0.44.0
	github.com/spf13/cobra v1.10.2
	golang.org/x/oauth2 v0.35.0
)
`
