package codegen

const mainTemplateSource = `// Code generated by clihub v{{.ClihubVersion}}. DO NOT EDIT.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcpclient "github.com/mark3labs/mcp-go/client"
{{- if .IsHTTP}}
	"github.com/mark3labs/mcp-go/client/transport"
{{- end}}
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/spf13/cobra"
)

// --- Embedded server configuration ---
{{- if .IsHTTP}}
const serverURL = {{quote .ServerURL}}
{{- else}}
var stdioCommand = {{quote .StdioCommand}}
var stdioArgs = {{quoteSlice .StdioArgs}}
var envKeys = {{quoteSlice .EnvKeys}}
{{- end}}

// --- Global flags ---
var (
	globalTimeout   int
	globalOutput    string
	globalAuthToken string
)

func main() {
	rootCmd := &cobra.Command{
		Use:   {{quote .CLIName}},
		Short: {{quote (printf "CLI for %s MCP server" .CLIName)}},
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	rootCmd.PersistentFlags().IntVarP(&globalTimeout, "timeout", "t", 30000, "per-call timeout in milliseconds")
	rootCmd.PersistentFlags().StringVarP(&globalOutput, "output", "o", "text", "output format: text|json|markdown|raw")
	rootCmd.PersistentFlags().StringVar(&globalAuthToken, "auth-token", "", "bearer token for authenticated MCP servers")

{{- range .Tools}}
	rootCmd.AddCommand(cmd{{funcName .Name}}())
{{- end}}

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}
}

// --- Tool commands ---
{{range .Tools}}
func cmd{{funcName .Name}}() *cobra.Command {
{{- range .Options}}
	var {{varName .FlagName}} {{.GoType}}
{{- end}}
	var flagRaw string

	cmd := &cobra.Command{
		Use:     {{quote .CommandName}},
		Aliases: []string{ {{quote .Name}} },
		Short:   {{quote .Description}},
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			params := make(map[string]interface{})
			if flagRaw != "" {
				if err := json.Unmarshal([]byte(flagRaw), &params); err != nil {
					return fmt.Errorf("invalid --raw JSON: %w", err)
				}
			} else {
{{- range .Options}}
{{- if eq .GoType "string"}}
				if {{varName .FlagName}} != "" {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "int"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "float64"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "bool"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "[]string"}}
				if len({{varName .FlagName}}) > 0 {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "[]int"}}
				if len({{varName .FlagName}}) > 0 {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- end}}
{{- end}}
			}
{{range .Options}}{{if .EnumValues}}
			// Validate enum for {{.FlagName}}
			if v, ok := params[{{quote .PropertyName}}]; ok {
				if s, ok := v.(string); ok {
					valid := {{quoteSlice .EnumValues}}
					found := false
					for _, e := range valid {
						if s == e {
							found = true
							break
						}
					}
					if !found {
						return fmt.Errorf("invalid value %q for --%s: must be one of: %s", s, {{quote .FlagName}}, strings.Join(valid, ", "))
					}
				}
			}
{{end}}{{end}}
			return callTool({{quote .Name}}, params)
		},
	}

{{- range .Options}}
	cmd.Flags().{{cobraFlag .GoType}}(&{{varName .FlagName}}, {{quote .FlagName}}, {{defaultLit .GoType .DefaultValue}}, {{quote (hasEnumDesc .Description .EnumValues)}})
{{- end}}
	cmd.Flags().StringVar(&flagRaw, "raw", "", "raw JSON arguments (bypasses all other flags)")

	return cmd
}
{{end}}

// --- MCP client via mcp-go SDK ---

func callTool(toolName string, params map[string]interface{}) error {
	token := lookupToken()

	timeout := time.Duration(globalTimeout) * time.Millisecond
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	c, err := createClient(token)
	if err != nil {
		return err
	}
	defer c.Close()

{{- if .IsHTTP}}
	// Start HTTP transport
	if err := c.Start(ctx); err != nil {
		if ctx.Err() != nil {
			return fmt.Errorf("tool call timed out after %dms", globalTimeout)
		}
		return fmt.Errorf("MCP connection failed: %w", err)
	}
{{- end}}

	// Initialize handshake
	initReq := mcp.InitializeRequest{}
	initReq.Params.ProtocolVersion = mcp.LATEST_PROTOCOL_VERSION
	initReq.Params.ClientInfo = mcp.Implementation{Name: {{quote .CLIName}}, Version: "1.0.0"}
	initReq.Params.Capabilities = mcp.ClientCapabilities{}

	if _, err := c.Initialize(ctx, initReq); err != nil {
		if ctx.Err() != nil {
			return fmt.Errorf("tool call timed out after %dms", globalTimeout)
		}
		return fmt.Errorf("MCP handshake failed: %w", err)
	}

	// Call tool
	callReq := mcp.CallToolRequest{}
	callReq.Params.Name = toolName
	callReq.Params.Arguments = params

	result, err := c.CallTool(ctx, callReq)
	if err != nil {
		if ctx.Err() != nil {
			return fmt.Errorf("tool call timed out after %dms", globalTimeout)
		}
		return fmt.Errorf("tool call failed: %w", err)
	}
	if result.IsError {
		// Extract error text from content
		var errTexts []string
		for _, content := range result.Content {
			if tc, ok := content.(mcp.TextContent); ok {
				errTexts = append(errTexts, tc.Text)
			}
		}
		if len(errTexts) > 0 {
			return fmt.Errorf("tool error: %s", strings.Join(errTexts, "\n"))
		}
		return fmt.Errorf("tool returned an error")
	}

	return formatOutput(result, globalOutput)
}

func createClient(token string) (*mcpclient.Client, error) {
{{- if .IsHTTP}}
	var opts []transport.StreamableHTTPCOption
	if token != "" {
		opts = append(opts, transport.WithHTTPHeaders(map[string]string{
			"Authorization": "Bearer " + token,
		}))
	}
	return mcpclient.NewStreamableHttpClient(serverURL, opts...)
{{- else}}
	// Build environment for subprocess
	env := os.Environ()
	for _, key := range envKeys {
		val := os.Getenv(key)
		if val == "" {
			return nil, fmt.Errorf("required environment variable %s is not set", key)
		}
	}
	return mcpclient.NewStdioMCPClient(stdioCommand, env, stdioArgs...)
{{- end}}
}

// --- Output formatting ---

func formatOutput(result *mcp.CallToolResult, format string) error {
	switch format {
	case "json":
		data, err := json.MarshalIndent(result, "", "  ")
		if err != nil {
			return err
		}
		fmt.Println(string(data))

	case "raw":
		data, err := json.Marshal(result)
		if err != nil {
			return err
		}
		fmt.Println(string(data))

	default: // "text", "markdown"
		text := extractText(result)
		fmt.Println(text)
	}
	return nil
}

func extractText(result *mcp.CallToolResult) string {
	var parts []string
	for _, content := range result.Content {
		switch c := content.(type) {
		case mcp.TextContent:
			parts = append(parts, c.Text)
		default:
			// For non-text content, marshal to JSON
			data, err := json.Marshal(c)
			if err == nil {
				var pretty bytes.Buffer
				if json.Indent(&pretty, data, "", "  ") == nil {
					parts = append(parts, pretty.String())
				} else {
					parts = append(parts, string(data))
				}
			}
		}
	}
	if len(parts) > 0 {
		return strings.Join(parts, "\n")
	}
	// Fallback: marshal the whole result
	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		return fmt.Sprintf("%+v", result)
	}
	return string(data)
}

// --- Auth ---

func lookupToken() string {
	// 1. Flag
	if globalAuthToken != "" {
		return globalAuthToken
	}

	// 2. Environment variable
	if token := os.Getenv("CLIHUB_AUTH_TOKEN"); token != "" {
		return token
	}

	// 3. Credentials file
	credPath := os.Getenv("CLIHUB_CREDENTIALS_FILE")
	if credPath == "" {
		home, err := os.UserHomeDir()
		if err == nil {
			credPath = filepath.Join(home, ".clihub", "credentials.json")
		}
	}
	if credPath != "" {
		data, err := os.ReadFile(credPath)
		if err == nil {
			var creds struct {
				Servers map[string]struct {
					Type        string ` + "`" + `json:"type"` + "`" + `
					Token       string ` + "`" + `json:"token"` + "`" + `
					AccessToken string ` + "`" + `json:"access_token"` + "`" + `
				} ` + "`" + `json:"servers"` + "`" + `
			}
			if json.Unmarshal(data, &creds) == nil {
{{- if .IsHTTP}}
				if s, ok := creds.Servers[serverURL]; ok {
					if s.Type == "oauth" && s.AccessToken != "" {
						return s.AccessToken
					}
					return s.Token
				}
{{- end}}
			}
		}
	}

	return ""
}
`

const goModTemplateSource = `module {{.CLIName}}

go 1.23

require (
	github.com/mark3labs/mcp-go v0.44.0
	github.com/spf13/cobra v1.10.2
)
`
