package codegen

const openAPIMainTemplateSource = `// Code generated by clihub v{{.ClihubVersion}}. DO NOT EDIT.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"golang.org/x/oauth2/google"
)

// --- Embedded API configuration ---
var defaultBaseURL = {{quote .BaseURL}}

// --- Global flags ---
var (
	globalTimeout        int
	globalOutput         string
	globalBaseURL        string
	globalAuthToken      string
	globalAuthType       string
	globalAuthHeaderName string
	globalAuthUsername   string
	globalAuthPassword   string
	globalHelpAuth       bool
)

func main() {
	rootCmd := &cobra.Command{
		Use:   {{quote .CLIName}},
		Short: {{quote (printf "CLI for %s API" .Title)}},
		SilenceUsage:  true,
		SilenceErrors: true,
	}

	rootCmd.PersistentFlags().IntVarP(&globalTimeout, "timeout", "t", 30000, "per-call timeout in milliseconds")
	rootCmd.PersistentFlags().StringVarP(&globalOutput, "output", "o", "text", "output format: text|json|raw")
	rootCmd.PersistentFlags().StringVar(&globalBaseURL, "base-url", "", "override the default base URL")
	rootCmd.PersistentFlags().StringVar(&globalAuthToken, "auth-token", "", "bearer token or API key")
	rootCmd.PersistentFlags().StringVar(&globalAuthType, "auth-type", "", "authentication type: bearer, api_key, basic, none")
	rootCmd.PersistentFlags().StringVar(&globalAuthHeaderName, "auth-header-name", "", "custom header name for api_key auth (default X-API-Key)")
	rootCmd.PersistentFlags().StringVar(&globalAuthUsername, "auth-username", "", "username for basic auth")
	rootCmd.PersistentFlags().StringVar(&globalAuthPassword, "auth-password", "", "password for basic auth")
	rootCmd.PersistentFlags().BoolVar(&globalHelpAuth, "help-auth", false, "show authentication flags and exit")
	hideAuthFlags(rootCmd)

{{- range .Operations}}
	rootCmd.AddCommand(cmd{{funcName .CommandName}}())
{{- end}}

	if wantsAuthHelp(os.Args[1:]) {
		printAuthFlagHelp(os.Stdout)
		return
	}

	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %s\n", err)
		os.Exit(1)
	}
}

func wantsAuthHelp(args []string) bool {
	for _, arg := range args {
		if arg == "--help-auth" || arg == "--help-auth=true" {
			return true
		}
	}
	return false
}

func hideAuthFlags(rootCmd *cobra.Command) {
	for _, name := range []string{
		"auth-token",
		"auth-type",
		"auth-header-name",
		"auth-username",
		"auth-password",
	} {
		_ = rootCmd.PersistentFlags().MarkHidden(name)
	}
}

func printAuthFlagHelp(out io.Writer) {
	fmt.Fprintln(out, "Authentication flags:")
	fmt.Fprintln(out, "  --auth-token string         bearer token or API key")
	fmt.Fprintln(out, "  --auth-type string          authentication type: bearer, api_key, basic, none")
	fmt.Fprintln(out, "  --auth-header-name string   custom header name for api_key auth (default X-API-Key)")
	fmt.Fprintln(out, "  --auth-username string      username for basic auth")
	fmt.Fprintln(out, "  --auth-password string       password for basic auth")
	fmt.Fprintln(out, "  --base-url string           override the default base URL")
}

func chooseFromJSONFlagName(cmd *cobra.Command) string {
	for _, candidate := range []string{"from-json", "clihub-from-json", "from-json-input"} {
		if cmd.Flags().Lookup(candidate) == nil {
			return candidate
		}
	}
	return "clihub-from-json"
}

// --- API operation commands ---
{{range .Operations}}
func cmd{{funcName .CommandName}}() *cobra.Command {
{{- range .AllParams}}
	var {{varName .FlagName}} {{.GoType}}
{{- end}}
	var flagFromJSON string
	fromJSONFlagName := "from-json"

	cmd := &cobra.Command{
		Use:   {{quote .CommandName}},
		Short: {{quote .Description}},
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			params := make(map[string]interface{})
			if flagFromJSON != "" {
				var conflictingFlag string
{{- range .AllParams}}
				if conflictingFlag == "" && cmd.Flags().Changed({{quote .FlagName}}) {
					conflictingFlag = {{quote .FlagName}}
				}
{{- end}}
				if conflictingFlag != "" {
					return fmt.Errorf("--%s cannot be combined with --%s", fromJSONFlagName, conflictingFlag)
				}
				if err := json.Unmarshal([]byte(flagFromJSON), &params); err != nil {
					return fmt.Errorf("invalid --%s JSON: %w", fromJSONFlagName, err)
				}
			} else {
{{- range .AllParams}}
{{- if eq .GoType "string"}}
				if {{varName .FlagName}} != "" {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "int"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "float64"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "bool"}}
				if cmd.Flags().Changed({{quote .FlagName}}) {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "[]string"}}
				if len({{varName .FlagName}}) > 0 {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- else if eq .GoType "[]int"}}
				if len({{varName .FlagName}}) > 0 {
					params[{{quote .PropertyName}}] = {{varName .FlagName}}
				}
{{- end}}
{{- end}}
			}
{{range .AllParams}}{{if .EnumValues}}
			// Validate enum for {{.FlagName}}
			if v, ok := params[{{quote .PropertyName}}]; ok {
				if s, ok := v.(string); ok {
					valid := {{quoteSlice .EnumValues}}
					found := false
					for _, e := range valid {
						if s == e {
							found = true
							break
						}
					}
					if !found {
						return fmt.Errorf("invalid value %q for --%s: must be one of: %s", s, {{quote .FlagName}}, strings.Join(valid, ", "))
					}
				}
			}
{{end}}{{end}}
			return callAPI({{quote .Method}}, {{quote .Path}}, params,
				{{quoteSlice (pathParamNames .PathParams)}},
				{{quoteSlice (queryParamNames .QueryParams)}},
				{{quoteSlice (headerParamNames .HeaderParams)}},
				{{.HasBody}})
		},
	}

{{- range .AllParams}}
	cmd.Flags().{{cobraFlag .GoType}}(&{{varName .FlagName}}, {{quote .FlagName}}, {{defaultLit .GoType .DefaultValue}}, {{quote (hasEnumDesc .Description .EnumValues)}})
{{- end}}
	fromJSONFlagName = chooseFromJSONFlagName(cmd)
	cmd.Flags().StringVar(&flagFromJSON, fromJSONFlagName, "", "request input as JSON (bypasses typed flags)")

	return cmd
}
{{end}}

// --- HTTP API client ---

func callAPI(method, pathTemplate string, params map[string]interface{}, pathParamNames, queryParamNames, headerParamNames []string, hasBody bool) error {
	provider := resolveAuthProvider()

	timeout := time.Duration(globalTimeout) * time.Millisecond
	ctx := (&http.Client{}).Timeout // unused, just to suppress lint
	_ = ctx

	baseURL := defaultBaseURL
	if globalBaseURL != "" {
		baseURL = globalBaseURL
	}
	baseURL = strings.TrimRight(baseURL, "/")

	// Substitute path parameters.
	path := pathTemplate
	for _, name := range pathParamNames {
		v, ok := params[name]
		if !ok {
			return fmt.Errorf("missing required path parameter: %s", name)
		}
		path = strings.ReplaceAll(path, "{"+name+"}", fmt.Sprintf("%v", v))
	}

	// Build query string.
	query := url.Values{}
	for _, name := range queryParamNames {
		v, ok := params[name]
		if !ok {
			continue
		}
		switch val := v.(type) {
		case []string:
			for _, s := range val {
				query.Add(name, s)
			}
		case []int:
			for _, n := range val {
				query.Add(name, fmt.Sprintf("%d", n))
			}
		case []interface{}:
			for _, item := range val {
				query.Add(name, fmt.Sprintf("%v", item))
			}
		default:
			query.Set(name, fmt.Sprintf("%v", val))
		}
	}

	fullURL := baseURL + path
	if len(query) > 0 {
		fullURL += "?" + query.Encode()
	}

	// Build request body from remaining params (body params).
	var bodyReader io.Reader
	if hasBody {
		bodyMap := make(map[string]interface{})
		bodyParamSet := make(map[string]bool)
		for _, name := range pathParamNames {
			bodyParamSet[name] = true
		}
		for _, name := range queryParamNames {
			bodyParamSet[name] = true
		}
		for _, name := range headerParamNames {
			bodyParamSet[name] = true
		}
		for k, v := range params {
			if !bodyParamSet[k] {
				bodyMap[k] = v
			}
		}
		if len(bodyMap) > 0 {
			data, err := json.Marshal(bodyMap)
			if err != nil {
				return fmt.Errorf("marshal request body: %w", err)
			}
			bodyReader = bytes.NewReader(data)
		}
	}

	client := &http.Client{Timeout: timeout}
	req, err := http.NewRequest(method, fullURL, bodyReader)
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}

	if hasBody && bodyReader != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	req.Header.Set("Accept", "application/json")

	// Set header parameters.
	for _, name := range headerParamNames {
		if v, ok := params[name]; ok {
			req.Header.Set(name, fmt.Sprintf("%v", v))
		}
	}

	// Apply auth headers.
	for k, v := range provider.getHeaders(req.Context()) {
		req.Header.Set(k, v)
	}

	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read response: %w", err)
	}

	if resp.StatusCode >= 400 {
		return fmt.Errorf("HTTP %d: %s", resp.StatusCode, string(respBody))
	}

	return formatOutput(respBody, resp.Header.Get("Content-Type"), globalOutput)
}

// --- Output formatting ---

func formatOutput(body []byte, contentType, format string) error {
	switch format {
	case "json":
		// Pretty-print JSON if possible.
		var pretty bytes.Buffer
		if json.Indent(&pretty, body, "", "  ") == nil {
			fmt.Println(pretty.String())
		} else {
			fmt.Println(string(body))
		}

	case "raw":
		os.Stdout.Write(body)

	default: // "text"
		// Try to pretty-print JSON, otherwise print as-is.
		if isJSON(contentType) {
			var pretty bytes.Buffer
			if json.Indent(&pretty, body, "", "  ") == nil {
				fmt.Println(pretty.String())
				return nil
			}
		}
		fmt.Println(string(body))
	}
	return nil
}

func isJSON(contentType string) bool {
	return strings.Contains(contentType, "json")
}

// --- Auth provider dispatch ---

type authProvider interface {
	getHeaders(ctx interface{}) map[string]string
}

type noAuthProvider struct{}
func (p *noAuthProvider) getHeaders(_ interface{}) map[string]string { return nil }

type bearerTokenProvider struct{ token string }
func (p *bearerTokenProvider) getHeaders(_ interface{}) map[string]string {
	if p.token == "" { return nil }
	return map[string]string{"Authorization": "Bearer " + p.token}
}

type apiKeyProvider struct{ token, headerName string }
func (p *apiKeyProvider) getHeaders(_ interface{}) map[string]string {
	if p.token == "" { return nil }
	name := p.headerName
	if name == "" { name = "X-API-Key" }
	return map[string]string{name: p.token}
}

type basicAuthProvider struct{ username, password string }
func (p *basicAuthProvider) getHeaders(_ interface{}) map[string]string {
	if p.username == "" && p.password == "" { return nil }
	encoded := base64.StdEncoding.EncodeToString([]byte(p.username + ":" + p.password))
	return map[string]string{"Authorization": "Basic " + encoded}
}

type s2sOAuth2Provider struct {
	clientID, clientSecret, tokenEndpoint string
	cachedToken string
	expiresAt   time.Time
}
func (p *s2sOAuth2Provider) getHeaders(_ interface{}) map[string]string {
	if p.cachedToken == "" || (!p.expiresAt.IsZero() && time.Now().After(p.expiresAt)) {
		token, expiresIn, err := s2sAuthenticate(p.tokenEndpoint, p.clientID, p.clientSecret)
		if err != nil {
			return nil
		}
		p.cachedToken = token
		if expiresIn > 0 {
			p.expiresAt = time.Now().Add(time.Duration(expiresIn) * time.Second)
		}
	}
	return map[string]string{"Authorization": "Bearer " + p.cachedToken}
}

type googleSAProvider struct {
	keyFile string
	scopes  []string
}
func (p *googleSAProvider) getHeaders(_ interface{}) map[string]string {
	keyData, err := os.ReadFile(p.keyFile)
	if err != nil { return nil }
	scopes := p.scopes
	if len(scopes) == 0 {
		scopes = []string{"https://www.googleapis.com/auth/cloud-platform"}
	}
	creds, err := google.CredentialsFromJSON(nil, keyData, scopes...)
	if err != nil { return nil }
	token, err := creds.TokenSource.Token()
	if err != nil { return nil }
	return map[string]string{"Authorization": "Bearer " + token.AccessToken}
}

// --- S2S OAuth2 ---

func s2sAuthenticate(tokenEndpoint, clientID, clientSecret string) (string, int, error) {
	form := url.Values{
		"grant_type":    {"client_credentials"},
		"client_id":     {clientID},
		"client_secret": {clientSecret},
	}

	req, err := http.NewRequest("POST", tokenEndpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return "", 0, err
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return "", 0, fmt.Errorf("S2S token request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		body, _ := io.ReadAll(resp.Body)
		return "", 0, fmt.Errorf("S2S token endpoint returned %d: %s", resp.StatusCode, string(body))
	}

	var tokenResp struct {
		AccessToken string ` + "`" + `json:"access_token"` + "`" + `
		ExpiresIn   int    ` + "`" + `json:"expires_in"` + "`" + `
	}
	if err := json.NewDecoder(resp.Body).Decode(&tokenResp); err != nil {
		return "", 0, fmt.Errorf("parse S2S response: %w", err)
	}
	if tokenResp.AccessToken == "" {
		return "", 0, fmt.Errorf("S2S response missing access_token")
	}
	return tokenResp.AccessToken, tokenResp.ExpiresIn, nil
}

// --- Credential store types ---

type credentialsFile struct {
	Version int                         ` + "`" + `json:"version,omitempty"` + "`" + `
	Servers map[string]serverCredential ` + "`" + `json:"servers"` + "`" + `
}

type serverCredential struct {
	AuthType      string   ` + "`" + `json:"auth_type,omitempty"` + "`" + `
	Type          string   ` + "`" + `json:"type,omitempty"` + "`" + `
	Token         string   ` + "`" + `json:"token,omitempty"` + "`" + `
	AccessToken   string   ` + "`" + `json:"access_token,omitempty"` + "`" + `
	HeaderName    string   ` + "`" + `json:"header_name,omitempty"` + "`" + `
	Username      string   ` + "`" + `json:"username,omitempty"` + "`" + `
	Password      string   ` + "`" + `json:"password,omitempty"` + "`" + `
	KeyFile       string   ` + "`" + `json:"key_file,omitempty"` + "`" + `
	Scopes        []string ` + "`" + `json:"scopes,omitempty"` + "`" + `
	ClientID      string   ` + "`" + `json:"client_id,omitempty"` + "`" + `
	ClientSecret  string   ` + "`" + `json:"client_secret,omitempty"` + "`" + `
	TokenEndpoint string   ` + "`" + `json:"token_endpoint,omitempty"` + "`" + `
}

func (s serverCredential) resolveAuthType() string {
	if s.AuthType != "" { return s.AuthType }
	switch s.Type {
	case "bearer": return "bearer_token"
	default: return s.Type
	}
}

// resolveAuthProvider builds an auth provider using the following priority:
//  1. --auth-type + auth flags -> explicit provider
//  2. --auth-token without --auth-type -> bearer (backwards compat)
//  3. CLIHUB_AUTH_TOKEN env var -> bearer
//  4. Credentials file -> provider from stored auth_type
//  5. No credentials -> no auth
func resolveAuthProvider() authProvider {
	// 1. Explicit --auth-type
	if globalAuthType != "" {
		switch globalAuthType {
		case "bearer", "bearer_token":
			return &bearerTokenProvider{token: globalAuthToken}
		case "api_key":
			return &apiKeyProvider{token: globalAuthToken, headerName: globalAuthHeaderName}
		case "basic", "basic_auth":
			return &basicAuthProvider{username: globalAuthUsername, password: globalAuthPassword}
		default:
			return &noAuthProvider{}
		}
	}

	// 2. --auth-token without --auth-type -> infer bearer
	if globalAuthToken != "" {
		return &bearerTokenProvider{token: globalAuthToken}
	}

	// 3. CLIHUB_AUTH_TOKEN env var
	if token := os.Getenv("CLIHUB_AUTH_TOKEN"); token != "" {
		return &bearerTokenProvider{token: token}
	}

	// 4. Credentials file
	credPath := os.Getenv("CLIHUB_CREDENTIALS_FILE")
	if credPath == "" {
		home, err := os.UserHomeDir()
		if err == nil {
			credPath = filepath.Join(home, ".clihub", "credentials.json")
		}
	}
	if credPath != "" {
		data, err := os.ReadFile(credPath)
		if err == nil {
			var creds credentialsFile
			if json.Unmarshal(data, &creds) == nil && creds.Servers != nil {
				baseURL := defaultBaseURL
				if globalBaseURL != "" {
					baseURL = globalBaseURL
				}
				if s, ok := creds.Servers[baseURL]; ok {
					authType := s.resolveAuthType()
					switch authType {
					case "bearer_token":
						return &bearerTokenProvider{token: s.Token}
					case "api_key":
						return &apiKeyProvider{token: s.Token, headerName: s.HeaderName}
					case "basic_auth":
						return &basicAuthProvider{username: s.Username, password: s.Password}
					case "s2s_oauth2":
						return &s2sOAuth2Provider{
							clientID: s.ClientID, clientSecret: s.ClientSecret,
							tokenEndpoint: s.TokenEndpoint,
						}
					case "google_sa":
						return &googleSAProvider{keyFile: s.KeyFile, scopes: s.Scopes}
					}
				}
			}
		}
	}

	// 5. No auth
	return &noAuthProvider{}
}
`

const openAPIGoModTemplateSource = `module {{.CLIName}}

go 1.24

require (
	github.com/spf13/cobra v1.10.2
	golang.org/x/oauth2 v0.35.0
)
`
